### ISSUE TITLE
Why need new ElasticSearch() every time creating an index?

### ISSUE THREAD

**Issue by silentred** [fadion/Bouncy#12]
Please check on this line. https://github.com/fadion/Bouncy/blob/l5/src/Fadion/Bouncy/BouncyTrait.php#L588

I dont understand why it is done this way instead of using an existing Client from IoC container?

**Comment by fadion** [comment]
It was written before registering the ElasticSearch client with the ioc and it remained like that. Except that the same method is written in 2 different classes, there's really no problem. However, if you want, you can create a pull request.

Checkout the [l5 branch](https://github.com/fadion/Bouncy/tree/l5); it needs to be updated too.
