### ISSUE TITLE
where does data stored?

### ISSUE THREAD

**Issue by argb** [fadion/Bouncy#16]
what's the default data path?I can't find it anywhere.

**Comment by argb** [comment]
i found it ,at /var/elasticsearch, and elasticsearch.php config file's setup don't work,don't know why? there is no log data generate in storage directory.

**Comment by fadion** [comment]
Bouncy uses a [PHP Client](https://github.com/elastic/elasticsearch-php) for ElasticSearch, which by default is configured to write logs to `storage_path().'/logs/elasticsearch.log'` for a level of `warning`. Probably you aren't getting any warnings or errors, so no logs are written.
