### ISSUE TITLE
Custom Analyzers

### ISSUE THREAD

**Issue by apsdehal** [fadion/Bouncy#4]
Is there a way to add custom analyzers while indexing? Like I want to use nGram tokenizer to analyze.

**Comment by fadion** [comment]
Tokenizers/analyzers are set on the index settings and that's out of scope for Bouncy. I could add such a functionality, but it would be a direct interface to the low level ElasticSearch client and wouldn't provide much of a value. You can build indexes with [indeces()->create()](https://github.com/elasticsearch/elasticsearch-php#create-an-index) and provide your own settings, including the tokenizer.

Bouncy exposes an `Elastic` facade for the low level client. Basically, you'd have something like below. I personally prefer to place such operations in an artisan command, so I have them handy whenever I need to rebuild an index.

``` php
$params['index'] = 'my_index';
$params['body']['settings']['analysis'] = [
  'analyzer' => [
    'myngram' => [
      'tokenizer' => 'myngramtokenizer'
    ]
  ],
  'tokenizer' => [
    // ...
  ]
];

Elastic::indices()->create($params);
```

As for applying the analyzer to a field, you can do that with Bouncy's mappings. They are set as simple model properties.

Let me know if I missed something.

**Comment by apsdehal** [comment]
Thanks a lot. It was really helpful.
