### ISSUE TITLE
Transform

### ISSUE THREAD

**Issue by AzzAToTV** [fadion/Bouncy#5]
Can you add support to modify what data get's put into Elasticsearch, like in  Elasticquent.

**Comment by fadion** [comment]
I'm not sure I understand. Can you elaborate?

**Comment by AzzAToTV** [comment]
Currently in your package, when you put the data into Elasticsearch you call $this->toArray(), i was wondering if you could add an overwritable function that gets the function, so i can change what array gets stored.

Elasticquent has it: 
https://github.com/adamfairholm/Elasticquent/#document-data

**Comment by fadion** [comment]
Just pushed a commit. Give it a try and let me know.

**Comment by Mochaka** [comment]
I'll let you know

**Comment by Mochaka** [comment]
Yes this works exactly as wanted, thanks!

**Comment by AzzAToTV** [comment]
Yes, this works exactly as expected. Thank you :+1:
